# Name: Maintenane
# Author: VaroWz
# Version: 2.0.1
# Support: https://discord.gg/SbKrKehCpq
# Discord: Antoine#4185
# Price: 1€
# Donate: paypal.me/antoinebw

Maintenance: false

Items:
  Enable:
    type: WOOL
    name: "&2&lEnable the &a&lMaintenance"
    lore: "&7Click to enable the maintenance"
    quantity: 1
    data: 13
  Disable:
    type: WOOL
    name: "&4&lDisable the &c&lMaintenance"
    lore: "&7Click to disable the maintenance"
    quantity: 1
    data: 14

Messages:

  Prefix: "&f[&2Maintenance&f] &7"

  NoPerm: "&cYou don't have permission to do this."
  GuiMaintenanceName: "&2&lMaintenance &7>>"
  MaintenanceEnableLog: "&7&lMaintenance ENABLE"
  MaintenanceDisableLog: "&7&lMaintenance DISABLE"
  MaintenanceEnableTitle: "&2&lMaintenance &a&lEnabled !"
  MaintenanceAlreadyEnable: "&cThe maintenance is already &aenabled"
  MaintenanceAlreadyDisable: "&cThe maintenance is already &cdisable"
  SuccesEnable: "&aThe maintenance is now &aenable"
  SuccesDisable: "&aThe maintenance is now &cdisable"
  PlayerKick: "&4&lThe server is under maintenance, come back later..."
  PlayerBypass: "&2You have permission to stay on the server."